name: Docker Ubuntu

on:  
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker run --rm -it -p 13389:3389 -p 10022:22 --shm-size=256m Biangkerok32/ubuntu-rdp:0.1.1
      
    - name: Keep Alive.
      run: ping 127.0.0.1 > null
